CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'hcakmak'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'hcakmak'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';
